- views/widgets/widget-pager.html.twig
- added **active** class on widget-pager twig template. So the user knows on which page he currently is.
> WID-160 - add active class on active page in twig template

- views/widgets/event-summary-grid.html.twig
- views/widgets/search-form-widget/group-filter-select_multiple.html.twig
- removed dummy class. 
- fixed checkboxes layout issue in group filters
> WID-209 - removed dummy class

- views/widgets/event-summary.html.twig
- views/widgets/search-results-widget/detail-page.html.twig
- changed icon in 'taaliconen' back to cnw-fa-language
> WID-226 - change icon of taaliconen back to cnw-fa-language

- .github/pull_request_template.md
- add pull-request template, same as udb3
> add pull-request template

- src/Widget/Twig/TwigPreprocessor.php
- remove strtolower on publisher
Ticket: [https://jira.uitdatabank.be/browse/WID-244](https://jira.uitdatabank.be/browse/WID-244)
> fix issue with publisher setting, remove strtolower on publisher

- .gitignore
- .vscode/settings.json
- views/widgets/search-results-widget/articles.html.twig
- changed layout / structure of articles section in widget 
---
Ticket: [https://jira.uitdatabank.be/browse/WID-243](https://jira.uitdatabank.be/browse/WID-243)
> WID-243 - change layout of article section in widget

- web/assets/js/widgets/core/tracking.js
- fix some code syntax issues, since this could cause issues in IE10
---
Ticket: [https://jira.uitdatabank.be/browse/WID-253](https://jira.uitdatabank.be/browse/WID-253)
> WID-253 - fix some code syntax issues

- src/Project/EventListener/ProjectCrudEventListener.php
- removed brief=true param so live key gets updated via insighly api
---
Ticket: [https://jira.uitdatabank.be/browse/PROJ-120](https://jira.uitdatabank.be/browse/PROJ-120)
> PROJ-120 - remove brief=true param so live key gets updated

- views/widgets/search-results-widget/articles.html.twig
- fixed issue with undefined publisherLogo
---
Ticket: [https://jira.uitdatabank.be/browse/WID-259](https://jira.uitdatabank.be/browse/WID-259)
> WID-259 - fixed issue with publisherLogo

- views/widgets/search-form-widget/search-form-widget.html.twig
- disable autcomplete on datepicker input fields in search-form widget.
---
Ticket: [https://jira.uitdatabank.be/browse/WID-282](https://jira.uitdatabank.be/browse/WID-282)
> WID-282 - disable autocomplete on datepicker input fields

- locales/en.yml
- locales/fr.yml
- locales/nl.yml
- add question mark in 'how do I get here' translation.
---
Ticket: [https://jira.uitdatabank.be/browse/WID-263](https://jira.uitdatabank.be/browse/WID-263)
> WID-263 add question mark in translation

- locales/region/en.yml
- locales/region/fr.yml
Missing translation
Incorrect translation
---
Ticket: WID-297
> Add missing translations

- locales/en.yml
- locales/fr.yml
- locales/nl.yml
- locales/when/en.yml
- locales/when/fr.yml
- locales/when/nl.yml
- src/Widget/EventListener/SearchResultsQueryAlterListener.php
- src/Widget/Twig/TwigPreprocessor.php
- src/Widget/WidgetType/SearchForm.php
- translate performed search queries
---
Ticket: [https://jira.uitdatabank.be/browse/WID-295](https://jira.uitdatabank.be/browse/WID-295)
> WID-295 - translate performed search queries

- locales/eventtype/en.yml
- locales/eventtype/fr.yml
- locales/eventtype/nl.yml
- src/Widget/Twig/TwigPreprocessor.php
added missing locale for 'en'
---
Ticket: [https://jira.uitdatabank.be/browse/WID-262](https://jira.uitdatabank.be/browse/WID-262)
> WID-262 - added missing locale for 'en'

- src/Widget/LayoutInterface.php
- src/Widget/Renderer.php
- src/Widget/RendererInterface.php
- src/Widget/Translation/Service/FilterForKeyWithFallback.php
- src/Widget/Translation/Service/TranslateTerm.php
- src/Widget/Translation/TranslationTwigExtension.php
- src/Widget/Twig/TwigPreprocessor.php
- src/Widget/WidgetLayout/LayoutBase.php
- src/Widget/WidgetLayout/OneCol.php
- src/Widget/WidgetLayout/ThreeColDoubleSidebar.php
- src/Widget/WidgetLayout/ThreeColTripple.php
- src/Widget/WidgetLayout/TwoColSidebarLeft.php
- src/Widget/WidgetLayout/TwoColSidebarRight.php
- src/Widget/WidgetType/Facets.php
- src/Widget/WidgetType/Html.php
- src/Widget/WidgetType/SearchForm.php
- src/Widget/WidgetType/SearchResults.php
- src/Widget/WidgetType/Tips.php
- src/Widget/WidgetType/WidgetTypeBase.php
- src/Widget/WidgetTypeInterface.php
- make preferredLanguage argument nullable
> hotfix - make preferredLanguage argument nullable

- src/Widget/Controller/WidgetController.php
- fixed issues with encoding
---
Ticket: [https://jira.uitdatabank.be/browse/WID-301](https://jira.uitdatabank.be/browse/WID-301)
> WID-301 - fix issue with encoding

- src/Widget/WidgetType/SearchForm.php
- src/Widget/WidgetTypeInterface.php
- fix for when preferredLanguage is not defined
---
Ticket: [https://jira.uitdatabank.be/browse/BILL-155](https://jira.uitdatabank.be/browse/BILL-155)
> BILL-155 - added fix for when preferredLanguage is not defined

- locales/language-icons/nl.yml
- fixed typo
---
Ticket: [https://jira.uitdatabank.be/browse/WID-316](https://jira.uitdatabank.be/browse/WID-316)
> WID-316 - fix typo

- src/Widget/Twig/TwigPreprocessor.php
- added utmParams to detail link
---
Ticket: [https://jira.uitdatabank.be/browse/WID-333](https://jira.uitdatabank.be/browse/WID-333)
> WID-333 - add utmParams to detail link of tip widget

- src/Widget/WidgetType/Tips.php
- embed multiple tips 
---
Ticket: [https://jira.uitdatabank.be/browse/WID-320](https://jira.uitdatabank.be/browse/WID-320)
> WID-320 - embed multiple tips

- views/widgets/event-summary.html.twig
- views/widgets/search-results-widget/detail-page.html.twig
- use event name instead of description
---
Ticket: [https://jira.uitdatabank.be/browse/WID-336](https://jira.uitdatabank.be/browse/WID-336)
> WID-336 - use event name instead of description

- app/Project/ProjectProvider.php
- removed permission_groups from ProjectProvider.php
---
Ticket: [https://jira.uitdatabank.be/browse/PROJ-140](https://jira.uitdatabank.be/browse/PROJ-140)
> PROJ-140 follow-up removed permission_groups from ProjectProvider.php

- integration_types.dist.yml
- widgets doc url in example config
---
Ticket: [https://jira.uitdatabank.be/browse/PROJ-147](https://jira.uitdatabank.be/browse/PROJ-147)
> PROJ-147 - Change widgets doc url in example config

- src/Widget/Migration/PushWidgetMigration.php
- src/Widget/Migration/SearchResultWidgetMigration.php
- src/Widget/ODM/Types/PageRows.php
- Convert old default_image setting value to new format
- Remove legacy migration code
---
Ticket: [https://jira.uitdatabank.be/browse/WID-340](https://jira.uitdatabank.be/browse/WID-340)
> WID-340 - Remove legacy migration code

- src/Widget/JavascriptResponse.php
- Use DOM manipulation to append widget content instead of document.write if possible
---
Ticket: https://jira.uitdatabank.be/browse/WID-365
> WID-365 - Use DOM manipulation instead of document.write if possible

- src/Widget/WidgetType/SearchResults.php
- views/widgets/search-results-widget/detail-page.html.twig
- Show type and theme labels on detail page if enabled
---
Ticket: https://jira.uitdatabank.be/browse/WID-364
> WID-364 - Show type and theme labels on detail page if enabled

- config.dist.yml
- phpunit.xml
- src/Insightly/InsightlyClient.php
- src/Insightly/InsightlyClientInterface.php
- src/Insightly/Item/Address.php
- src/Insightly/Item/Contact.php
- src/Insightly/Item/Link.php
- src/Insightly/Item/Organisation.php
- src/Insightly/Item/PrimaryEntityBase.php
- test/Insightly/InsightlyIntegrationTest.php
- test/Insightly/Item/AddressTest.php
- test/Insightly/Item/ContactTest.php
- test/Insightly/Item/ProjectTest.php
- Take into account the changed contact info on Insightly API v3
- Take into account the changed address structure on Insightly API v3
- Take into account the changed structure for links on Insightly API v3
- Update links when creating or updating a project (links are the related contact and the related organisation)
Note: this pull request does not fix the internal structure to only support a single contact info or a single address. This only focuses on fixing the integration with Insightly API v3
Note: some delete methods were added to avoid polluting the integrated Insightly environment
---
Ticket: https://jira.uitdatabank.be/browse/PROJ-153
> PROJ-153 Upgrade to insightly api v3 (contacts)

- .github/workflows/ci.yml
- src/Widget/Twig/TwigPreprocessor.php
- Images: changed value of crop param to `edges`
---
Ticket: https://jira.uitdatabank.be/browse/WID-324
> WID-324 - Changed crop param to edges

- src/Insightly/Parser/LinkParser.php
- Take into account new format of links
---
Ticket: https://jira.uitdatabank.be/browse/PROJ-176
> PROJ-176 Take into account new format of links

- src/Widget/WidgetType/SearchForm.php
- Removed quotes around free text search terms
---
Ticket: https://jira.uitdatabank.be/browse/WID-378
> WID-378 Remove quotes around free text search terms

- src/Widget/Twig/TwigPreprocessor.php
- Fixed cropping of default images
---
Ticket: https://jira.uitdatabank.be/browse/WID-374
> WID-374 Fix image cropping of default images

- web/assets/js/widgets/core/widgets.js
- Only encode the square brackets instead of all URL parameters
---
Ticket: https://jira.uitdatabank.be/browse/WID-375
> WID-375 Only encode the square brackets instead of all URL parameters

- web/assets/js/widgets/core/widgets.js
- Make sure to replace all brackets 😅
---
Ticket: https://jira.uitdatabank.be/browse/WID-375
> WID-375 Replace all square brackets

- src/Widget/WidgetType/SearchForm.php
- Using multiple words should result in an `AND` free text search
---
Ticket: https://jira.uitdatabank.be/browse/WID-378
> WID-378 Multiple words result in an AND search

- web/assets/js/widgets/core/widgets.js
- Fixed typo when for right square bracket
- Make sure to use `replaceAll`
---
Ticket: https://jira.uitdatabank.be/browse/WID-378
> WID-378 Fix typo

- src/Widget/WidgetType/SearchForm.php
- web/assets/js/widgets/core/widgets.js
- Fixed broken filters
Notes:
- This is not reproducible locally
- This happens on production with "older" widgets, newly created widgets still work
---
Ticket: https://jira.uitdatabank.be/browse/WID-390
> WID-390 Fix broken filters

- app/Core/CacheProvider.php
- app/Core/CoreProvider.php
- app/Core/HttpClient.php
- app/WidgetMigration/WidgetMigrationProvider.php
- composer.json
- composer.lock
- Replace culturefeed-http-guzzle dependency with simple internal class
---
Ticket: https://jira.uitdatabank.be/browse/PROJ-182
> PROJ-182 Replace culturefeed http guzzle

- composer.lock
- Fix multiple advanced search parameter
---
Ticket: https://jira.uitdatabank.be/browse/WID-394
> WID-394 Fix multiple advanced search parameter

- src/Widget/WidgetType/SearchForm.php
- web/assets/js/widgets/core/widgets.js
- Enabled square brackets conversion again (See: https://jira.uitdatabank.be/browse/WID-375)
- Enabled searching with AND again (See: https://jira.uitdatabank.be/browse/WID-378)
---
Ticket: https://jira.uitdatabank.be/browse/WID-390
> WID-390 Enable fixes for square brackets and search with AND again

- composer.json
- composer.lock
- config.dist.yml
- phpcs-ruleset.xml
- phpunit.integrations.insightly.xml
- phpunit.xml
- src/Integrations/Insightly/Exceptions/AuthenticationFailed.php
- src/Integrations/Insightly/Exceptions/BadRequest.php
- src/Integrations/Insightly/Exceptions/DeleteFailed.php
- src/Integrations/Insightly/Exceptions/RecordLimitReached.php
- src/Integrations/Insightly/Exceptions/RecordNotFound.php
- src/Integrations/Insightly/InsightlyClient.php
- src/Integrations/Insightly/PipelineStages.php
- src/Integrations/Insightly/Serializers/ContactSerializer.php
- src/Integrations/Insightly/Serializers/OpportunitySerializer.php
- src/Integrations/Insightly/ValueObjects/Contact.php
- src/Integrations/Insightly/ValueObjects/Description.php
- src/Integrations/Insightly/ValueObjects/Email.php
- src/Integrations/Insightly/ValueObjects/FirstName.php
- src/Integrations/Insightly/ValueObjects/Id.php
- src/Integrations/Insightly/ValueObjects/IntegrationType.php
- src/Integrations/Insightly/ValueObjects/LastName.php
- src/Integrations/Insightly/ValueObjects/Name.php
- src/Integrations/Insightly/ValueObjects/Opportunity.php
- src/Integrations/Insightly/ValueObjects/OpportunityStage.php
- src/Integrations/Insightly/ValueObjects/OpportunityState.php
- test/Integrations/Insightly/InsightlyClientTest.php
- Added Insightly integration for a `Contact`
- Added Insightly integration for an `Opportunity`
Note: Follow-up ticket to link a `Contact` with an `Opportunity` https://jira.uitdatabank.be/browse/PROJ-185
---
Ticket: https://jira.uitdatabank.be/browse/PROJ-159
> PROJ-159 Create Insightly opportunity

- src/Integrations/Insightly/InsightlyClient.php
- src/Integrations/Insightly/PipelineStages.php
- src/Integrations/Insightly/Resources/ContactResource.php
- src/Integrations/Insightly/Resources/OpportunityResource.php
- src/Integrations/Insightly/Resources/ProjectResource.php
- src/Integrations/Insightly/Serializers/OpportunitySerializer.php
- src/Integrations/Insightly/Serializers/ProjectSerializer.php
- src/Integrations/Insightly/ValueObjects/Coupon.php
- src/Integrations/Insightly/ValueObjects/Project.php
- src/Integrations/Insightly/ValueObjects/ProjectStage.php
- src/Integrations/Insightly/ValueObjects/ProjectStatus.php
- test/Integrations/Insightly/InsightlyClientTest.php
- Added Insightly integration for `Project`
---
Ticket: https://jira.uitdatabank.be/browse/PROJ-160
> PROJ-160 Create Insightly project

- src/Integrations/Insightly/Resources/OpportunityResource.php
- src/Integrations/Insightly/Resources/ProjectResource.php
- src/Integrations/Insightly/Serializers/OpportunitySerializer.php
- src/Integrations/Insightly/ValueObjects/Opportunity.php
- test/Integrations/Insightly/InsightlyClientTest.php
- A `Contact` is now required on an `Opportunity` and stored as a Insightly Link
---
Ticket: https://jira.uitdatabank.be/browse/PROJ-185
> PROJ-185 Link contact to opportunity

- src/Integrations/Insightly/Resources/OpportunityResource.php
- src/Integrations/Insightly/Resources/ProjectResource.php
- src/Integrations/Insightly/Serializers/LinkSerializer.php
- src/Integrations/Insightly/Serializers/OpportunitySerializer.php
- src/Integrations/Insightly/Serializers/ProjectSerializer.php
- src/Integrations/Insightly/ValueObjects/Project.php
- test/Integrations/Insightly/InsightlyClientTest.php
- Extended `Project` with a required `Contact`
- Created `LinkSerializer` for serialization of an embedded `Contact` on `Project` and `Opportunity`
---
Ticket: https://jira.uitdatabank.be/browse/PROJ-186
> PROJ-186 link contact with project

- src/Integrations/Insightly/InsightlyClient.php
- src/Integrations/Insightly/Resources/OrganizationResource.php
- src/Integrations/Insightly/Serializers/OpportunitySerializer.php
- src/Integrations/Insightly/Serializers/OrganizationSerializer.php
- src/Integrations/Insightly/Serializers/ProjectSerializer.php
- src/Integrations/Insightly/ValueObjects/Address.php
- src/Integrations/Insightly/ValueObjects/Organization.php
- src/Integrations/Insightly/ValueObjects/TaxNumber.php
- test/Integrations/Insightly/InsightlyClientTest.php
- Added `Organization` integration for Insightly
Note: Link between `Organization` and `Opportunity` will be done in a follow-up PR, also see https://jira.uitdatabank.be/browse/PROJ-188
---
Ticket: https://jira.uitdatabank.be/browse/PROJ-161
> PROJ-161 Create Insightly Organization integration

- src/Integrations/Insightly/Serializers/CustomFieldSerializer.php
- src/Integrations/Insightly/Serializers/OpportunitySerializer.php
- src/Integrations/Insightly/Serializers/OrganizationSerializer.php
- src/Integrations/Insightly/Serializers/ProjectSerializer.php
- Created a dedicated class `CustomFieldSerializer` to handle the custom fields in a more generic way and reuse some logic.
---
Ticket: https://jira.uitdatabank.be/browse/PROJ-161
> PROJ-161 Refactor custom fields

- app/config/messagebus.yml
- src/Project/CommandHandler/RequestActivationCommandHandler.php
- src/Project/Event/RequestedActivation.php
- src/Project/EventListener/ProjectActivatedEventListener.php
- src/Project/EventListener/ProjectBlockedEventListener.php
- src/Project/EventListener/ProjectCreatedEventListener.php
- src/Project/EventListener/ProjectCrudEventListener.php
- src/Project/EventListener/ProjectDeletedEventListener.php
- src/Project/EventListener/RequestedActivationEventListener.php
- test/Project/CommandHandler/RequestActivationCommandHandlerTest.php
- Moved the Insightly code from the command handler `RequestActivationCommandHandler` to an event handler `RequestedActivationEventListener` which listens to `RequestedActivation`
Note: In a follow-up pull request the new Insightly integration will be added based on `RequestedActivation`
---
Ticket: https://jira.uitdatabank.be/browse/PROJ-161
> PROJ-161 Activate project without coupon with event listener

- app/Integrations/Insightly/InsightlyServiceProvider.php
- app/config/messagebus.yml
- src/Entity/Project.php
- src/Integrations/Insightly/GroupIdConverter.php
- src/Integrations/Insightly/Resources/ContactResource.php
- src/Integrations/Insightly/Resources/OpportunityResource.php
- src/Integrations/Insightly/Resources/OrganizationResource.php
- src/Integrations/Insightly/Resources/ProjectResource.php
- src/Integrations/Insightly/Serializers/CustomFieldNotFound.php
- src/Integrations/Insightly/Serializers/CustomFieldSerializer.php
- src/Integrations/Insightly/Serializers/LinkSerializer.php
- src/Integrations/Insightly/Serializers/OrganizationSerializer.php
- src/Integrations/Insightly/Serializers/ProjectSerializer.php
- src/Integrations/Insightly/ValueObjects/Opportunity.php
- src/Integrations/Insightly/ValueObjects/Project.php
- src/Project/EventListener/Insightly/ProjectCreatedListener.php
- src/Project/EventListener/Insightly/RequestedActivationListener.php
- src/Project/ProjectService.php
- test/Integrations/Insightly/InsightlyClientTest.php
- Added method to get Organization based on tax number
- Added method to get Organization based on the accounting Email
- Added method to link an Organization to a Project
- Added method to create an Organization with a linked contact and organization
- Added listener for handling RequestedActivation inside the new Insightly instance
- Removed the `getById` method for Organizations
---
Ticket: https://jira.uitdatabank.be/browse/PROJ-161
> PROJ-161 Add new RequestedActivation listener

- src/Project/EventListener/Insightly/ProjectActivatedListener.php
- Allow activation without coupon as admin
---
Ticket: https://jira.uitdatabank.be/browse/PROJ-162
> PROJ-163 Activate as admin without coupon

- app/config/messagebus.yml
- src/Integrations/Insightly/Resources/ProjectResource.php
- src/Integrations/Insightly/ValueObjects/Project.php
- src/Project/EventListener/Insightly/ProjectActivatedListener.php
- src/Project/EventListener/Insightly/ProjectBlockedListener.php
- src/Project/EventListener/Insightly/RequestedActivationListener.php
- test/Integrations/Insightly/InsightlyClientTest.php
- Add new listener for `ProjectBlocked` with integration on new Insightly instance
---
Ticket: https://jira.uitdatabank.be/browse/PROJ-164
> PROJ-164 Block a project or opportunity as admin

- app/config/messagebus.yml
- src/Entity/Project.php
- src/Entity/ProjectInterface.php
- src/Project/EventListener/Insightly/ProjectDeletedListener.php
- test/Integrations/Insightly/InsightlyClientTest.php
- Added listener for `ProjectDeleted` to handle the update inside the new Insightly instance
---
Ticket: https://jira.uitdatabank.be/browse/PROJ-165
> PROJ-165 Handle project deleted

- app/Project/ProjectControllerProvider.php
- src/Integrations/Insightly/Resources/OrganizationResource.php
- src/Project/Controller/ProjectController.php
- test/Project/Controller/ProjectControllerTest.php
- Make it possible to get organization from new Insightly instance
---
Ticket: https://jira.uitdatabank.be/browse/PROJ-183
> PROJ-183 Get organization from new Insightly instance

- src/Integrations/Insightly/Resources/OrganizationResource.php
- src/Integrations/Insightly/Serializers/OrganizationSerializer.php
- src/Project/Controller/ProjectController.php
- test/Integrations/Insightly/InsightlyClientTest.php
- Added method to update an organization inside Insightly
---
Ticket: https://jira.uitdatabank.be/browse/PROJ-184
> PROJ-184 Update organization

- src/Integrations/Insightly/Resources/OrganizationResource.php
- src/Project/EventListener/Insightly/ProjectActivatedListener.php
- src/Project/EventListener/Insightly/RequestedActivationListener.php
- test/Integrations/Insightly/InsightlyClientTest.php
- Link a contact with an organization at creation time.
---
Ticket: https://jira.uitdatabank.be/browse/PROJ-191
> PROJ-191 Link contact with organization

- app/ConsoleApplication.php
- src/Console/Command/MigrateInsightlyIds.php
- Added migration script for Insightly Ids
---
Ticket: https://jira.uitdatabank.be/browse/PROJ-189
> PROJ-189 Add migration script for Insightly Ids

- src/Widget/WidgetType/SearchResults.php
- Show "when" information in detail by adding calendar summary parameters to detail request
---
Ticket: https://jira.uitdatabank.be/browse/WID-398
> WID-398 Show when in detail

- src/Project/EventListener/Insightly/RequestedActivationListener.php
- Change opportunity state from won to open after a request
---
Ticket: https://jira.uitdatabank.be/browse/PROJ-198
> PROJ-198 Change opportunity state from won to open after a request

- src/Widget/WidgetType/Tips.php
- missing calsum on tips widget
---
Ticket: https://jira.uitdatabank.be/browse/WID-411
> WID-411 - Fixed missing calsum on tips widget

- .github/workflows/ci.yml
- src/Widget/WidgetType/Tips.php
- Use wildcard for availableTo and availableFrom after search V3 upgrade
- Run CI only for PHP 7.4
---
Ticket:  https://jira.uitdatabank.be/browse/WID-412
> III-412 Fix Tip Widget after Search V3 upgrade

- app/config/messagebus.yml
- src/Project/CommandHandler/CreateProjectCommandHandler.php
- src/Project/EventListener/Insightly/ProjectCreatedListener.php
- test/Project/CommandHandler/CreateProjectCommandHandlerTest.php
- Added extra logging for command and event handling of project creation
> Add extra logging for command and event handling of project creation

- views/widgets/widget-pager.html.twig
- widgets-static/app/templates/partials/search_result-pagination.html
- Add extra classes on paginator buttons
---
Ticket: https://jira.uitdatabank.be/browse/WID-404
> WID-404 Add extra classes on paginator buttons

- views/widgets/facility-summary.html.twig
- Add clip for facility called "Aanwezig" and "Niet aanwezig"
Note: took the Font Awesome approach https://fontawesome.com/v5.15/how-to-use/on-the-web/other-topics/accessibility
---
Ticket: https://jira.uitdatabank.be/browse/WID-428
> WID-428 Add clip for facility called "Aanwezig" and "Niet aanwezig"

- views/widgets/facility-summary.html.twig
- views/widgets/search-results-widget/detail-page.html.twig
- web/assets/js/widgets/search-results/search-results.js
- Add aria-expanded for toggles
---
Ticket: https://jira.uitdatabank.be/browse/WID-427
> WID-427 Add aria-expanded for toggles

- src/Widget/Twig/TwigPreprocessor.php
- Prevent replacing comma with dot on the name of a price
---
Ticket: https://jira.uitdatabank.be/browse/WID-425
> WID-425 Prevent replacing comma with dot on the name of a price

- src/Utility/TextProcessingTrait.php
- test/Utility/TextProcessingTraitTest.php
- Fix truncating html tags
---
Ticket: https://jira.uitdatabank.be/browse/WID-436
> WID-436 Fix truncating html tags

- src/Widget/WidgetType/SearchResults.php
- Remove videos setting from items
---
Ticket: https://jira.uitdatabank.be/browse/WID-230
> III-230 Remove videos setting from items

- src/Widget/Twig/TwigPreprocessor.php
- Prevent crash when videos are missing
> Hotfix for crash when videos are missing

- locales/region/de.yml
' Wallonisch-Brabant into Wallonisch-Brabant
--- 
Ticket: https://jira.uitdatabank.be/browse/WID-444
> Fix syntax error

- locales/region/de.yml
Province names (some of them were still in french)
---
Ticket: https://jira.uitdatabank.be/browse/WID-444
> Correct province names

- src/Widget/WidgetType/Facets.php
- broken facilities filters
---
Ticket: https://jira.uitdatabank.be/browse/WID-447
> WID-447 - Fix broken facilities filters

- web/assets/js/widgets/core/placeholder-load.js
- web/assets/js/widgets/core/widgets.js
- Dispatch custom events 
---
Ticket: https://jira.uitdatabank.be/browse/WID-460
> WID-460 - Dispatch custom events for widget integrators

- src/Widget/WidgetType/Facets.php
- theme not being removed properly from the url
---
Ticket: https://jira.uitdatabank.be/browse/WID-456
> WID-456 - Fix theme not being removed properly from the url

- web/assets/js/widgets/core/placeholder-load.js
- web/assets/js/widgets/core/widgets.js
- Dispatch custom event for when tip results are loaded
- Tip widget: fIx loading of events when there's an anchor in the url
---
Ticket: https://jira.uitdatabank.be/browse/WID-461
> WID-461 - Fix tips widget when anchor in url

- src/Widget/Twig/TwigPreprocessor.php
- web/assets/js/widgets/core/widgets.js
- facebook share link
---
Ticket: https://jira.uitdatabank.be/browse/WID-481
> WID-481 - Fix facebook share link

- web/assets/js/widgets/core/widgets.js
- share when search filters are active
---
Ticket: https://jira.uitdatabank.be/browse/WID-487
> WID-487 - Fix share when search filters are active

- web/assets/js/widgets/core/snowplow-tracking.js
> WID-478 - Fix wrong schema

- web/assets/js/widgets/core/snowplow-tracking.js
-  Fix wrong name impressions schema
---
> WID-478 - Fix wrong name impressions schema

- web/assets/js/widgets/core/snowplow-tracking.js
- Send event_impresions as an array
---
> WID-478 - Send event_impresions as an array

- web/assets/js/widgets/core/snowplow-tracking.js
- Temporary add console.logs for debugging
> WID-478 - Temporary add console.logs for debugging

- src/Widget/Renderer.php
- web/assets/js/widgets/core/snowplow-tracking.js
- web/assets/js/widgets/core/widgets.js
- not loading of widget by adding a initSnowplow method on the CultuurnetWidgets prototype
---
Ticket: https://jira.uitdatabank.be/browse/WID-501
> WID-501 - Fix not loading of widget by adding a initSnowplow method

- composer.lock
- locales/de.yml
- locales/en.yml
- locales/fr.yml
- locales/nl.yml
- src/Widget/Twig/TwigPreprocessor.php
- views/widgets/event-summary.html.twig
- views/widgets/search-results-widget/detail-page.html.twig
- Show "Online" in a search result for an event with online attendance mode
- Show the "OnlineUrl" in an event detail when the online url is not empty
---
Ticket: https://jira.uitdatabank.be/browse/WID-485
> WID-485 Add online url to search and detail

- web/assets/js/widgets/core/snowplow-tracking.js
-  Only send cdbid if defined
---
> WID-478 - Only send cdbid if defined

- web/assets/js/widgets/core/snowplow-tracking.js
> WID-478 - Increase schema version

- web/assets/js/widgets/core/snowplow-tracking.js
> WID-478 - Add logs for debugging

- web/assets/js/widgets/core/snowplow-tracking.js
> WID-478 - Fix typo

- src/Utility/TextProcessingTrait.php
- src/Widget/Twig/TwigPreprocessor.php
- Broken description truncate based on character count
---
Ticket: https://jira.uitdatabank.be/browse/WID-410
> WID-410 - Fix broken description truncate based on character count

- views/widgets/event-summary.html.twig
- views/widgets/search-results-widget/detail-page.html.twig
-  video icon for online events
---
Ticket: https://jira.uitdatabank.be/browse/WID-507
> WID-507 - Add video icon for online events

- src/Widget/WidgetType/SearchResults.php
- Add missing description annotations for detail page in SeachResults
---
Ticket: https://jira.uitdatabank.be/browse/WID-410
> WID-410 - Add missing description annotations for detail page

- src/Widget/WidgetType/Facets.php
> #336: Check for valid facet input

- src/Widget/WidgetType/Tips.php
- Fix tips widget to support foreign countries
---
Ticket: https://jira.uitdatabank.be/browse/WID-539
> WID-539 - Fix tips widget to support foreign countries

- locales/fr.yml
- locales/theme/fr.yml
- Add spaces before french punctuation (+ some typo fixes)
---
Ticket: https://jira.uitdatabank.be/browse/III-5292
> Add spaces before french punctuation (+ some typo fixes)

- .github/CODEOWNERS
- app/Widget/WidgetServiceProvider.php
- src/Widget/JavascriptResponse.php
- src/Widget/WidgetType/SearchForm.php
- Added port number to URLs inside widget code
- Added code owners
---
> PPF-192 Add port number to URLs inside widget code

- app/Widget/WidgetServiceProvider.php
- src/Widget/JavascriptResponse.php
- src/Widget/WidgetType/SearchForm.php
This reverts commit 18da7e4186901d4dcfaa7c5cacda6b7d6fb4a35c.
- Removed port number from URLs inside widget code
---
Ticket: https://jira.uitdatabank.be/browse/PPF-192
> PPF-192: Revert "Add port number to URLs inside widget code"

- app/ConsoleApplication.php
- app/Core/MessageBusProvider.php
- src/Console/Command/ConsumeCommand.php
- Define the exchange in the `config` instead of hardcoded `main_exchange`
To work on test, the code needs this PR first: https://github.com/cultuurnet/appconfig/pull/465
---
> PPF-192 new exchange no delay

- src/Widget/WidgetType/SearchForm.php
- src/Widget/WidgetType/SearchResults.php
- Do not use legacy order for join() or implode()
---
> PPF-192 Do not use legacy order for join() or implode()

- docker.md
- Use correct exchange name
---
> PPF-192 Use correct exchange name

- Makefile
- src/Entity/Project.php
- `Makefile`: new command to update database
- `Database`: add new column `platform_uuid` to table `project`
---
> PPF-230 add column for Platform Uuid

- src/Project/CommandHandler/ImportProjectCommandHandler.php
- test/Project/CommandHandler/ImportProjectCommandHandlerTest.php
- Refactored endPoint `ImportProject` to handle updates.
- Added unit test for `ImportProjectCommandHandler` to differentiate between creating and updating an ImportedProject
---
> PPF-230 update project from PPF in ProjectAanvraag

- docker-compose.yml
- Changed ports to avoid port conflicts with publiq-platform
---
> PPF-230 Avoid port conflicts with publiq-platform

- app/Project/ProjectControllerProvider.php
- app/WebApplication.php
- src/Project/Controller/ImportProjectController.php
- src/Project/Controller/OpenProjectController.php
- test/Project/Controller/ImportProjectControllerTest.php
- Added `ProjectRepository` to `OpenProject()`
- The correct WidgetProject is now opened from `publiq-platform`
---
> PPF-230 add projectRepository to OpenProject

- app/ApplicationBase.php
- app/Platform/PlatformClient.php
- app/Platform/PlatformClientInterface.php
- app/Platform/PlatformServiceProvider.php
- app/Project/ProjectControllerProvider.php
- app/User/UserServiceProvider.php
- app/WebApplication.php
- src/Entity/Project.php
- src/Entity/ProjectInterface.php
- src/Project/Controller/OpenProjectController.php
- src/User/UserService.php
- src/Voter/ProjectVoter.php
- test/User/UserServiceTest.php
- test/Voter/ProjectVoterTest.php
- Added delegation of project access to publiq-platform to also take into account contacts
- Also requires this new toggle to be enabled https://github.com/cultuurnet/appconfig/pull/509
---
Ticket: https://jira.publiq.be/browse/PPF-236
> PPF-236 Delegate project access to publiq-platform

- app/Project/ProjectControllerProvider.php
- app/WebApplication.php
- src/Project/Controller/OpenProjectController.php
- Improve regex for new project imports endpoint. This regex did conflict with `request-activation` which is not public
---
> PPF-230 Fixed regex for project paths

- views/widgets/event-summary.html.twig
- [mailto to booking info email](https://github.com/cultuurnet/projectaanvraag-silex/commit/f4fef8d92ba180033266e02a9b77519e02e24c26)
---
Ticket: https://jira.publiq.be/browse/WID-558
> WID-558 - Add mailto to booking info email

- src/Widget/Twig/TwigPreprocessor.php
- Make vlieg logo logic consistent with vlieg events filter
---
Ticket: https://jira.publiq.be/browse/WID-563
> WID-563 - Make vlieg logo logic consistent with vlieg events filter

- proxies/__CG__CultuurNetProjectAanvraagEntityUser.php
- Replaced deprecated array_key_exists by property_exists
---
Ticket: https://jira.publiq.be/browse/WID-566
> WID-566 - Replace deprecated array_key_exists by property_exists

- src/Widget/WidgetType/SearchResults.php
- src/Widget/WidgetType/Tips.php
- test/Widget/data/page.json
- Don't show icon_uitx by default
---
Ticket: https://jira.publiq.be/browse/WID-568
> WID-568 - Don't show icon_uitx by default

- src/Widget/Twig/TwigPreprocessor.php
- [Fix typo](https://github.com/cultuurnet/projectaanvraag-silex/commit/20b9011c852b94455f3ce74b3f09201fc921393d)
---
Ticket: https://jira.publiq.be/browse/WID-563
> WID-563 - Fix typo

- .github/workflows/ci.yml
- removed workflow for `PHP 7,1`
---
> PROJ-233: update workflow

- composer.json
- composer.lock
- updated `cweagans/composer-patches` from `1.6.5` to `1.7.3`, in preparation for adding `sentry`
---
> PROJ-233: updated cweagans/composer-patches

- composer.json
- composer.lock
> PROJ-233: updated doctrine

- composer.json
- composer.lock
- Updated `guzzlehttp/guzzle`
---
> PROJ-233: Updated guzzlehttp/guzzle

- composer.json
- composer.lock
- Updated `jdesrosiers/silex-cors-provider`
---
> PROJ-233 update jdesrosiers/silex-cors-provider

- composer.json
- composer.lock
- update `kevinrob/guzzle-cache-middleware`
---
> PROJ-233: update kevinrob/guzzle-cache-middleware

- composer.json
- composer.lock
> PROJ-233: update ml/json-ld

- composer.json
- composer.lock
> PROJ-233: update symfony

- app/ApplicationBase.php
- app/Sentry/SentryServiceProvider.php
- composer.json
- composer.lock
- src/ArticleLinker/ArticleLinkerClient.php
- src/ArticleLinker/ArticleLinkerClientInterface.php
- src/Core/Event/ConsumerTypeInterface.php
- src/Core/Event/QueueConsumers.php
- src/Core/Event/SyncConsumer.php
- src/Coupon/CouponValidator.php
- src/Coupon/CouponValidatorInterface.php
- src/Entity/Project.php
- src/Project/Controller/ProjectController.php
- src/Project/ProjectService.php
- src/User/User.php
- src/Widget/Converter/WidgetPageConverter.php
- src/Widget/EventListener/SearchResultsQueryAlterListener.php
- src/Widget/Twig/TwigPreprocessor.php
-  Added `Sentry` to composer
---
> PROJ-233: Add Sentry to composer

- src/ShareProxy/Controller/ShareProxyController.php
- Checked description to avoid crash on null value
---
Ticket: https://jira.publiq.be/browse/PROJ-236
> PROJ-236 Check description to avoid crash on null value

- .github/pull_request_template.md
- src/Widget/Twig/TwigPreprocessor.php
- Avoid notice by checking existence of origin
---
Ticket: https://jira.publiq.be/browse/PROJ-235
> PROJ-235 Check if origin is set

- .github/CODEOWNERS
Added Simon and myself as codeowners because I noticed I missed PR's for this project.
> Adding Simon and Koen as codeowners

- docker.md
- docker/config.sh
- `config.sh`:  Add `host.docker.internal` via `make config`
- `docker.md`: update info about `host.docker.internal`
---
Ticket: https://jira.uitdatabank.be/browse/III-6155
> III-6155 update /etc/hosts via config

- web/robots.txt
---
Ticket: https://jira.publiq.be/browse/WID-571
> Add robots.txt to disallow indexing of projectaanvraag-api and social.uit.be

- . gitattributes
- Ignored CSS as main language
> Ignore CSS as main language

- . gitattributes
> Disable css for linguist

- src/Widget/WidgetType/Facets.php
- Updated Vlieg Query
- This doesn't retroactively fix the already created widgets.
---
Ticket: https://jira.publiq.be/browse/PROJ-240
> PROJ-240 Update Vlieg Query

- web/assets/js/widgets/search-form/search-form.js
- Accept empty value for search fields
---
Ticket: https://jira.publiq.be/browse/WID-584
> WID-584 Accept empty value for search fields

- docker/php/Dockerfile
- docker/php/custom-apache.conf
- Fixed Apache header size issues
> Fix header size issues

- views/widgets/event-summary.html.twig
- web/assets/js/widgets/core/snowplow-tracking.js
- Tracked title instead of read more
---
Ticket: https://jira.publiq.be/browse/PROJ-241
> PROJ-241 Track title instead of read more

- src/Widget/WidgetType/Facets.php
> Use correct annotation
