cultuurnet/projectaanvraag-silex

src/Widget/WidgetType/SearchResults.php

- added new setting in searchResults.php annotations so it accepts the setting "items" (integer). So the user can decide how many items he wants to show on the page.
- added new variable $results_per_page which will have the value of the items settings (if it exists) otherwise it will take the const ITEMS_PER_PAGE (which is set to 10).
- the query->setLimit now uses the $results_per_page param
- the query->setStart now uses the $results_per_page param

WID-213 - added new setting items (integer) in SearchResults.php

---

locales/region/en.yml
locales/region/fr.yml

- fix wrong name for waasland region
---
Ticket: [https://jira.uitdatabank.be/browse/WID-329](https://jira.uitdatabank.be/browse/WID-329)

WID-329 - fix wrong name for waasland region

---

web/assets/js/widgets/core/tracking.js
web/assets/js/widgets/core/widgets.js

- use https as fixed protocol for jquery + gtm
---
Ticket: [https://jira.uitdatabank.be/browse/WID-335](https://jira.uitdatabank.be/browse/WID-335)

WID-235 - use https as fixed protocol for jquery + gtm

---

src/Widget/Twig/TwigPreprocessor.php

- use "en" before last publisher in label instead of comma
- only show publishers once in editorial label
---
Ticket: [https://jira.uitdatabank.be/browse/WID-317](https://jira.uitdatabank.be/browse/WID-317)

WID-317 - bugfix, only show publishers once in editorial label

---

composer.lock

- The 2.x version of silex-uitid-provider was deleted and later recovered from a copy in a local vendor folder. The commit has changed though so it needs to be updated to one that exists now.
---
Spotted this in a Travis build where it was loading the package from cache because it couldn't find the commit anymore, while reviewing another PR.

Update silex-uitid-provider commit to one that exists

---

src/Widget/Twig/TwigPreprocessor.php

- Only use `lg` format for `single` calendar type, not `periodic` and `permanent`
---
Ticket: https://jira.uitdatabank.be/browse/WID-351
Follow-up to: #206

Only use lg format for single calendar type

---

composer.lock

- Fixed some fatal errors in specific situations by upgrading to search-v3 `v1.3.1`

Update search-v3 to fix some fatal errors

---

web/assets/js/widgets/core/widgets.js

- Encode the URL parameters to make sure brackets are encoded for servers who don't support plain square brackets inside the URL parameters
---
Ticket: https://jira.uitdatabank.be/browse/WID-375

WID-375 Encode the URL parameters to make sure brackets are encoded

---

src/Widget/WidgetType/SearchResults.php

- Use wildcard method after upgrading Search V3

Hotfix: Use wildcard method after upgrading searchv3

---

app/Core/CultureFeedServiceProvider.php

- Removed unnecessary `ConsumerCredentials` usage. We cannot remove `cultuurnet/auth` yet because we still use `cultuurnet/silex-uitid-provider`, but we will be able to remove that when we switch to Auth0 for login.

Remove unnecessary wrapping of culturefeed consumer key and secret

---

composer.json
src/Integrations/Insightly/Serializers/CustomFieldSerializer.php

- Fixed name for coupon field on production, needs to be `Coupon__c`
---
Ticket: https://jira.uitdatabank.be/browse/PROJ-195

PROJ-195 Rename Coupon_field__c to Coupon__c as on production

---

web/assets/js/widgets/core/widgets.js

- loading of searchresults when using anchor in url
http://localhost:8000/#random
Before:
After:
---
Ticket: https://jira.uitdatabank.be/browse/WID-459

WID-459 - Fix loading of searchresults when using anchor in url

---

web/assets/js/widgets/core/snowplow-tracking.js

- Snowplow error: `$.active_seconds: number found, integer expected\", \"path\": \"$.active_seconds\"`
---
Ticket:  https://jira.uitdatabank.be/browse/WID-478

WID-478 - Transform activeSeconds to integer to match snowplow scheme

---

web/assets/js/widgets/core/snowplow-tracking.js

- send event_impressions & active_seconds as 2 seperate selfdescribingEvents
- cdbid: send empty string when undefined
---

WID-478 - Snowplow fixes

---

views/widgets/event-summary.html.twig
views/widgets/search-results-widget/detail-page.html.twig

- Readd `map` icon for location
- Use `camera` icon for participation url
---
Ticket: https://jira.uitdatabank.be/browse/WID-507

WID-507 - use camera icon for online participation url

---

app/SearchAPI/SearchAPIServiceProvider.php

- Add X-Client-Properties to default headers sent with the SearchAPIClient
---
Ticket: https://jira.uitdatabank.be/browse/WID-543

WID-543 - Add X-Client-Properties to default headers sent with the SearchAPIClient

---

app/ConsoleApplication.php
app/Core/MessageBusProvider.php
src/Console/Command/ConsumeCommand.php

- Added support for enabling/disabling `delay` for `amqp`-messages via `config`
---

PPF-192 enable/disable delay via config

---

.github/dependabot.yml

- Automated dependency updates
This needs to be enabled in the project settings. Once enabled, automated updates will be suggested by dependabot.
Note: this differs from the Dependabot security updates that are already in place. It will also bump major versions of dependencies.
Please see the documentation for all configuration options: https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
---
Ticket:

Add automated dependabot updates

---

src/User/UserService.php

- Prevented runtime error on empty user array
---

Prevent runtime error on empty user array

---

views/widgets/search-results-widget/detail-page.html.twig

- [missing title on span](https://github.com/cultuurnet/projectaanvraag-silex/commit/bcbe1ce96450a1713d908ea45e1ceb35b83c5b71)
---
Ticket: https://jira.publiq.be/browse/WID-550

WID-550 - Added missing title on span

---

composer.lock

- Updated `twig/twig` from `v2.7.4` to `v2.16.0`
- Deprecated warning for `array_key_exists()` should no longer appear.
---
Ticket: https://jira.publiq.be/browse/WID-566

WID-566: Update twig/twig

---

app/Project/ProjectControllerProvider.php

- `ProjectControllerProvider`: make trailing slash optional when importing Projects from PPF.
- No more CORS-errors, when trying to create or open Widgets from PPF.
---
Ticket: https://jira.publiq.be/browse/PPF-423

PPF-423: Allow both trailing & no trailing slash when importing projects from PPF

---

src/Widget/Controller/WidgetController.php

- Use `origin`which is passed as an url param instead of the header referer. 
Since the referer is not reliable: the path is truncated from the referer. 
- This should fix the issue in which articles are linked to the homepage.
---
Ticket: https://jira.publiq.be/browse/WID-569

WID-569 - Fix wrong url passed to articleLinker

---

web/assets/js/widgets/core/snowplow-tracking.js

- Pass snowplow_tracker_name to avoid tracking on wrong instance
---
Ticket: https://jira.publiq.be/browse/UIT-2283

UIT-2283 - Use snowplow_tracker_name on events

---

web/assets/js/widgets/core/snowplow-tracking.js

- Rename snowplow instance on window to `widgetSnowplow` to avoid conflicts with snowplow instance of uiv
---
Ticket: https://jira.publiq.be/browse/UIT-2308

UIT-2308 - Rename snowplow instance on window to widgetSnowplow

---

src/Widget/RegionService.php
test/Widget/RegionServiceTest.php
test/Widget/regions_sample.json

- `RegionService`: Add logic for searching informal names.
- `regions_sample.json`: Added everything `*Molenbeek*`
- `RegionServiceTest`: Add test for matching on informal names.
---
Ticket: https://jira.publiq.be/browse/WID-575

WID-575 Molenbeek Edge case

---

src/Widget/WidgetType/Facets.php

- Import `WidgetType` to avoid runtime error

Import `WidgetType` to avoid runtime error

---

src/Widget/RegionService.php
test/Widget/RegionServiceTest.php
test/Widget/regions_sample.json

- [Improve autocomplete results for provinces](https://github.com/cultuurnet/projectaanvraag-silex/commit/b9c7f489586319b85b7e2a860edcbc0440ee85d6)
A search on `vlaams-brabant` should return results e.g. `provincie vlaams-brabant`
---
Ticket: https://jira.publiq.be/browse/WID-588

WID-588 - Improve autocomplete results for provinces
